# Generated by Django 4.2.1 on 2023-06-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название валюты')),
                ('short_name', models.CharField(max_length=50, verbose_name='Краткое название валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images', verbose_name='Фотография')),
                ('header', models.CharField(max_length=225, verbose_name='Заголовок')),
                ('description_text', models.TextField(verbose_name='Описание в виде json')),
                ('type_coffee', models.PositiveSmallIntegerField(choices=[('1', 'Зеленый кофе'), ('2', 'Обжаренный кофе')], unique=True, verbose_name='Тип кофе')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип кофе (мытый, сухой и т.д.)')),
            ],
            options={
                'verbose_name': 'Тип кофе',
                'verbose_name_plural': 'Типы кофе',
            },
        ),
        migrations.CreateModel(
            name='CoffeeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Сорт (название) коффе')),
                ('size', models.CharField(blank=True, max_length=255, verbose_name='Размер пачки')),
                ('grade', models.CharField(blank=True, default='', max_length=255, verbose_name='Оценка')),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='app.news', verbose_name='Кофе')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.currency', verbose_name='Валюта')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coffee_desc', to='app.treatment', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описании',
            },
        ),
    ]
