# Generated by Django 4.2.1 on 2023-06-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_news_type_coffee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description_text',
            new_name='description',
        ),
    ]
